#!/bin/sh
#

# a unicode locale is required
export LANG=en_US.UTF-8

FTP=/var/ftp/pub/cygwin
SRCDIR=`/usr/bin/dirname "$0"`

for arch in x86_64 x86 ; do
    TMPFILE=`/bin/mktemp -t setup.ini.${arch}XXX`
    INIFILE=${FTP}/${arch}/setup.ini

    SETUP_VERSION=`${SRCDIR}/extract-setup-version /www/sourceware/htdocs/cygwin/setup-${arch}.exe`

    ${SRCDIR}/calm --inifile ${TMPFILE} --setup-version ${SETUP_VERSION} --arch=${arch} --email
    if [ $? -eq 0 ]
    then
        # if changed in more than timestamp
        /usr/bin/diff -I^setup-timestamp -w -B -q ${INIFILE} ${TMPFILE} >/dev/null
        if [ $? -eq 1 ]
        then
            # update setup.ini
            /bin/mv ${TMPFILE} ${INIFILE}
            # compress
            /usr/bin/bzip2 <${INIFILE} >${INIFILE/%.ini/.bz2}
            # re-sign
            /bin/rm -f ${INIFILE}.sig ${INIFILE/%.ini/.bz2}.sig
            /usr/bin/gpg --batch --yes -b ${INIFILE}
            /usr/bin/gpg --batch --yes -b ${INIFILE/%.ini/.bz2}
            # arrange for checksums to be recomputed
            /bin/rm -f ${FTP}/${arch}/md5.sum ${FTP}/${arch}/sha512.sum
        fi
    fi
    /bin/rm -f ${TMPFILE}
done
