#!/usr/bin/env python3
#
# Copyright (c) 2015 Jon Turney
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# compare-arch - compare package sets between architectures
#

import argparse
import logging
import os
import sys

import common_constants
import maintainers
import package
import uploads


#
#
#
def make_package_list_filter(packages):
    def filter(p):
        if p.startswith('cygwin32') or p.startswith('cygwin64') or p.endswith('-debuginfo'):
            return False

        if '_obsolete' in packages[p].hints.get('category', ''):
            return False

        if 'skip' in packages[p].hints:
            return False

        return True

    return filter


#
#
#

def main(args):
    packages = {}
    pset = {}
    union = set()

    for arch in common_constants.ARCHES:
        # build package list
        packages[arch] = package.read_packages(args.rel_area, arch)

        # filter list
        l = filter(make_package_list_filter(packages[arch]), packages[arch].keys())

        # make a set of the package list
        pset[arch] = frozenset(l)

        # make the union of all the package lists
        union = union.union(pset[arch])

    # list packages missing from an arch
    for p in sorted(union):
        exists = {}

        for arch in common_constants.ARCHES:
            exists[arch] = p in packages[arch]

        # packages which exist in all arches
        if all(exists.values()):
            continue

        print("%s is only in arch %s" % (p, [a for a in exists if exists[a]]))

    # XXX: another way to do that...
    # find the set of packages which aren't in an arch
    for arch in common_constants.ARCHES:
        diff = union.difference(pset[arch])
        print("not in %s : %s" % (arch, ', '.join(sorted(diff))))

    # XXX: this requires unfiltered package lists
    # are there any packages which have a maintainer, but don't exist?
    mlist = maintainers.Maintainer.read(args)
    all_packages = maintainers.Maintainer.all_packages(mlist)

#    for p in sorted(all_packages):
#        if p not in union:
#            print("package '%s' has a maintainer, but doesn't exist in any architecture" % (p))

#
#
#

if __name__ == "__main__":
    homedir_default = common_constants.HOMEDIR
    pkglist_default = common_constants.PKGMAINT
    relarea_default = common_constants.FTP

    parser = argparse.ArgumentParser(description='Compare arch package sets')
    parser.add_argument('--homedir', action='store', metavar='DIR', help="maintainer home directory (default: " + homedir_default + ")", default=homedir_default)
    parser.add_argument('--pkglist', action='store', metavar='FILE', help="package maintainer list (default: " + pkglist_default + ")", default=pkglist_default)
    parser.add_argument('--releasearea', action='store', metavar='DIR', help="release directory (default: " + relarea_default + ")", default=relarea_default, dest='rel_area')
    parser.add_argument('-v', '--verbose', action='count', dest='verbose', help='verbose output')
    (args) = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.INFO)

    logging.basicConfig(format=os.path.basename(sys.argv[0])+': %(message)s')

    main(args)
