<div id="x86">
<div id="background">
<b class="rtop"><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b></b>
<h2>Available Packages for x86</h2>
<b class="rbottom"><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></b>
</div>
<br>
<table class="pkglist">
<tr><td><a href="x86/arc">arc</a></td><td>The ARC archive utility</td></tr>
<tr><td><a href="x86/base-cygwin">base-cygwin</a></td><td>Initial base installation helper script.</td></tr>
<tr><td><a href="x86/cygwin">cygwin</a></td><td>The UNIX emulation engine</td></tr>
<tr><td><a href="x86/cygwin-debuginfo">cygwin-debuginfo</a></td><td>Debug info for cygwin</td></tr>
<tr><td><a href="x86/cygwin-devel">cygwin-devel</a></td><td>Core development files</td></tr>
<tr><td><a href="x86/keychain">keychain</a></td><td>Key manager for OpenSSH</td></tr>
<tr><td><a href="x86/libdns_sd-devel">libdns_sd-devel</a></td><td>Bonjour Zeroconf implementation</td></tr>
<tr><td><a href="x86/libdns_sd1">libdns_sd1</a></td><td>Bonjour Zeroconf implementation</td></tr>
<tr><td><a href="x86/libtextcat-devel">libtextcat-devel</a></td><td>Helper, header and library for libtextcat</td></tr>
<tr><td><a href="x86/libtextcat0">libtextcat0</a></td><td>Text Classification Library dll</td></tr>
<tr><td><a href="x86/mDNSResponder">mDNSResponder</a></td><td>Bonjour Zeroconf implementation</td></tr>
<tr><td><a href="x86/proj-debuginfo">proj-debuginfo</a></td><td>Debug info for proj</td></tr>
</table>
</div>
